# Generated by Django 4.0.1 on 2022-04-05 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('num_users', models.IntegerField(default=1)),
                ('user_uuid', models.UUIDField(default=uuid.uuid4)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
    ]
